name: notey
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  uuid: ^4.3.0
  flutter_slidable: ^3.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  connectivity_plus: ^6.0.0
  google_fonts: ^6.2.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#13131B"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
